import { registerSW as register } from "virtual:pwa-register";

/**
 * Registers the service worker generated by vite-plugin-pwa.
 * autoUpdate strategy means a new SW takes over on the next page load.
 */
export function registerSW(): void {
  if (import.meta.env.DEV) return;
  if (!("serviceWorker" in navigator)) return;
  register({
    immediate: true,
    onRegisteredSW(swUrl) {
      console.info("[pwa] service worker registered:", swUrl);
    },
    onRegisterError(err) {
      console.warn("[pwa] service worker registration failed", err);
    },
  });
}
